### ISSUE TITLE
Reading SSTables from HDFS

### ISSUE THREAD

**Issue by GlaDos28** [jberragan/spark-cassandra-bulkreader#2]
Hello there, I found this pretty and the only library and tested it on a local file system, it actually worked. Then I stuck in implementing the same logic, but with Spark executors scaling.

I need to bulk read Cassandra data from given tables, given that the tables are put into HDFS the same way `LocalDataLayer` works. So far I achieved something by copying `LocalDataLayer` implementation and changing every use of filesystem paths from java paths to `hadoop.fs` path and `FileSystem` class, so basically to swap local filesystem interface with HDFS filesystem interface. The problem is that my implementation apparently works on a single partition with a single task, not scaling at all.

As I understand, I should derive from `PartitionedDataLayer`, but I want to ensure that I'm not missing anything:

– Is implementation of `PartitionedDataLayer` with the same user input parameters as `LocalDataSource` (`LocalDataLayer`) will be enough to achieve what I want?
– How You can estimate the difficulty of implementing such logic? You know your project a lot better than I, perhaps for You it is a lot more clear about resources needed to achieve my task.

`PartitionedDataLayer` seemed a bit complicated for me on the first glance, so if I should use another approach, I should know it in advance. I thoroughly explore ` S3DataLayer` to understand what common it has with my potential implementation.

At least if I achieve something useful with this task, I contribute it with PR.

**Comment by jberragan** [comment]
PartitionedDataLayer is a bit more complicated but yes that is exactly what you need to successfully shard the Spark workers and read in a scalable way.  You'll need to implement your own PartitionedDataLayer and your own DataSource to provide any Spark options you need to talk to HDFS.

You might find this S3 example useful: [s3](https://github.com/jberragan/spark-cassandra-bulkreader/tree/develop/example/src/org/apache/cassandra/spark/s3)

[S3DataLayer](https://github.com/jberragan/spark-cassandra-bulkreader/blob/develop/example/src/org/apache/cassandra/spark/s3/S3DataLayer.java) implements the PartitionedDataLayer, and [S3DataSource](https://github.com/jberragan/spark-cassandra-bulkreader/blob/develop/example/src/org/apache/cassandra/spark/s3/S3DataSource.java) is the equivalent DataSource implementation for S3DataLayer.

[S3Client](https://github.com/jberragan/spark-cassandra-bulkreader/blob/develop/example/src/org/apache/cassandra/spark/s3/S3Client.java) is just a helper wrapper around the standard s3 client for making calls to S3, and [S3Example](https://github.com/jberragan/spark-cassandra-bulkreader/blob/develop/example/src/org/apache/cassandra/spark/s3/S3Example.java) gives example usage.

The most important part of the PartitionedDataLayer is to:

- provide a CassandraRing object describing your Cassandra ring, instances & tokens
- provide a TokenPartitioner describing which Spark partitions own which parts C* token ring
- implement the listInstance method to list all the SSTables on a given Cassandra instance
- then implement your own DataLayer.SSTable implementation to open an InputStream on your SSTable file components in HDFS.

All I can say is it might look more complex than it really is. The bulletpoints above are the main APIs you need implement, I'd say try that, use the S3 example as a template, and keep iterating.

We use [SSTableInputStream](https://github.com/jberragan/spark-cassandra-bulkreader/blob/develop/core/src/org/apache/cassandra/spark/utils/streaming/SSTableInputStream.java) to read the SSTables in a scalable way without OOMing, but it's completely optional and depends on your data size, you can provide a normal InputStream if it scales.

Happy to answer any further questions or review any code.

**Comment by jberragan** [comment]
> – How You can estimate the difficulty of implementing such logic? You know your project a lot better than I, perhaps for You it is a lot more clear about resources needed to achieve my task.

**Comment by GlaDos28** [comment]
@jberragan I see. Took a closer look at `PartitionedDataLayer`, it seems to be rather tailored to `S3DataLayer` implementation. `SSTableInputStream` is too fitted for `S3` implementation. I see such things like "Cassandra Ring", "Replication", "Consistency level", "Data Center", "Network request" and etc. In my case all of it does not matter, as I work with SSTables purely as files, detached from Cassandra for good, so to speak. My task is more about "read a bunch of files with some internal structure to be parsed into DataFrame", rather than "read a bunch of data from Database into DataFrame". If I worked with CSV files, then I would need to give every executor the file path and range of rows to read, presuming we know row number of each CSV file. In case of Cassandra's SSTables, the task is actually the same, but SSTable's structure is far more complex than CSV, that is why I am searching a library to perform SSTable reading.

I expect to work with sizes withing the limits of 1Tb, for instance, I test bulk reading with one table and 53Gb of data. So yes, I need buffered input streaming from SSTables.

To conclude my thought, I need only some parts of logic to gather from `PartitionedDataLayer` and `SSTableInputStream`. Probably I will create own abstract class like `PartitionedDataLayer` that suits the only aspect of executioner scaling, but without any extra logic. Of course, I could use `PartitionedDataLayer` and just bypass the logic I don't need, but I'm afraid it will be more difficult that implementing the class for my own design. Let's see how things go.

**Comment by jberragan** [comment]
Yes, the PartitionedDataLayer assumes the SSTables are grouped into logical units the 'CassandraInstance', this is because it accepts a ConsistencyLevel - just like the normal C* clients - and will read from sufficient CassandraInstance replicas to achieve the desired consistency level. If you are reading the entire cluster from HDFS, you don't need this and can probably simplify a lot, it's the equivalent of doing a ConsistencyLevel ALL read.

It's not explicitly tied to the S3DataLayer, it's just an example implementation. We have our own internal implementation that reads the SSTables directly from a Cassandra cluster snapshot directory using the [Apache Cassandra Sidecar](https://github.com/apache/cassandra-sidecar) to serve the SSTable bytes over a secured http api (hope to open source eventually). For this reason we need ConsistencyLevel stuff to ensure we can read consistently even if a host is down for replacement.

SSTableInputStream is a special implementation of the JDK java.io.InputStream that buffers enough bytes from some 'source' interface and handles back pressure. Normally the CompactionIterator is slower than 'source' can provide the bytes so SSTableInputStream only requests more bytes when the buffer is drained - so preventing OOMs. It also has a more efficient skip() method implementation so we can skip out-of-range partitions or excluded columns without reading across the network.

**Comment by GlaDos28** [comment]
I ultimately decided to use straightforward way to read from Cassandra with Datastax Cassandra connector. I'm afraid it is too much time to afford docking this library to my project and my needs. Unfortunately I have no such time. But in case fastest reading will be more important for me, perhaps I return to this library.

Nevertheless, thanks for all the support! I close the issue.
